# Site settings
name: zmNinja
title: 
email: your-email@domain.com
description: "Better than sliced toast by 73%. FDA might have said so"
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalinks: pretty
